### ISSUE TITLE
Termsbox Discussion

### ISSUE THREAD

**Issue by ArchBlood** [humhub-contrib/termsbox#1]
In light of the Legal Tools module I don't really see much need of the Termsbox module anymore could it be safe to say that this module could be archived?

In the case of this module **_not_** getting archived here's some ideas
- Integrate an interface between both the Legal Tools module and this module
- Change the name and namespace to force confirmation(s), after all that is what this module forces on users

In the case of this module being archived
- It would be safe to say that the same logic could be applied to force users to accept/decline the Terms & Privacy Policy, meaning in the case that someone declines they are force logged out, whereas if they accept they can go on as usual

Just food for thought, as this module does things that the Legal Tools module **should** be doing but doesn't

**Comment by luke-** [comment]
II would prefer to mark the module as "Legacy" and archive this repo after a while.

**Comment by ArchBlood** [comment]
> II would prefer to mark the module as "Legacy" and archive this repo after a while.

If you wouldn't mind, I'd like to try my hand at merging some of the functions both of these modules have that the other doesn't, of course if it works how I'm wanting to, I'll send a p/r to the Legal Tools module for review

**Comment by luke-** [comment]
What exactly would you like to migrate from the Termsbox to the LegalTools module?

**Comment by ArchBlood** [comment]
Personally I'd like to migrate the `actionAccpet` & `actionDecline` while also looking into the reports of Legal Update not updating after multiple uses (See https://github.com/humhub-contrib/legal/issues/12)

https://github.com/humhub-contrib/termsbox/blob/f6f7d0e6c4372fbb2b91e6e80e39f0dfa3290e4b/controllers/IndexController.php#L21-L37

**Comment by luke-** [comment]
The accept is implemented, just a bit different:
https://github.com/humhub-contrib/legal/blob/master/models/RegistrationChecks.php#L167

#2 seems to be a bug, I'll check it out.
