### ISSUE TITLE
Must Change Password, breaks Termsbox

### ISSUE THREAD

**Issue by luke-** [humhub-contrib/termsbox#4]
![image](https://user-images.githubusercontent.com/4736168/134310425-b058ac5e-e1f7-4c01-8139-5374dad5c19d.png)

**Comment by yurabakhtin** [comment]
@luke- I decided to hide the termsbox on the "must change password" page, after user will changed password the termsbox will appers on next page. PR https://github.com/humhub-contrib/termsbox/pull/5.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
